const form=document.querySelector('#student-form'), database=document.querySelector('#database'), records=document.querySelector('#records'), status=document.querySelector('#status'), search=document.querySelector('#search'), cancel=document.querySelector('#cancel');
let students=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function load(){status.textContent='Loadingâ€¦';try{const r=await fetch(`/api/students?database=${database.value}`);const data=await r.json();if(!r.ok)throw Error(data.error);students=data;render();status.textContent=`${students.length} record(s)`;}catch(e){records.innerHTML=`<tr><td colspan="7">${esc(e.message)}</td></tr>`;status.textContent='Connection failed';}}
function render(){const term=search.value.toLowerCase();const visible=students.filter(s=>Object.values(s).join(' ').toLowerCase().includes(term));records.innerHTML=visible.length?visible.map(s=>{const id=encodeURIComponent(s.studentId);return `<tr><td>${esc(s.studentId)}</td><td>${esc(s.fullName)}</td><td>${esc(s.email)}</td><td>${esc(s.course)}</td><td>${s.yearLevel}</td><td>${esc(s.phone)}</td><td><button onclick="editStudent(decodeURIComponent('${id}'))">Edit</button><button class="danger" onclick="deleteStudent(decodeURIComponent('${id}'))">Delete</button></td></tr>`}).join(''):'<tr><td colspan="7">No matching students.</td></tr>';}
form.addEventListener('submit',async e=>{e.preventDefault();const values=new URLSearchParams(new FormData(form));values.set('database',database.value);status.textContent='Savingâ€¦';try{const r=await fetch('/api/students',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:values});const data=await r.json();if(!r.ok)throw Error(data.error);resetForm();await load();status.textContent='Student saved.';}catch(e){status.textContent=e.message;}});
function resetForm(){form.reset();form.studentId.readOnly=false;document.querySelector('#form-title').textContent='Add student';cancel.hidden=true;}
window.editStudent=id=>{const s=students.find(x=>x.studentId===id);for(const [k,v] of Object.entries(s))form.elements[k].value=v;form.studentId.readOnly=true;document.querySelector('#form-title').textContent='Edit student';cancel.hidden=false;window.scrollTo({top:0,behavior:'smooth'});};
window.deleteStudent=async id=>{if(!confirm(`Delete ${id}?`))return;try{const r=await fetch(`/api/students/${encodeURIComponent(id)}?database=${database.value}`,{method:'DELETE'});const data=await r.json();if(!r.ok)throw Error(data.error);await load();status.textContent='Student deleted.';}catch(e){status.textContent=e.message;}};
database.addEventListener('change',load);document.querySelector('#refresh').addEventListener('click',load);search.addEventListener('input',render);cancel.addEventListener('click',resetForm);load();

